### ISSUE TITLE
README.md renders incorrectly

### ISSUE THREAD

**Issue by ehuelsmann** [sjjf/md_server#11]
Hi,

Your README.md contains these lines:

```plain
- <userdata_dir>/<instance>
- <userdata_dir>/<instance>.yaml
- <userdata_dir>/<MAC>
- <userdata_dir>/<MAC>.yaml
```

Which is rendered in the HTML view on GitHub as:

```plain
- <userdata_dir>/
- <userdata_dir>/.yaml
- <userdata_dir>/
- <userdata_dir>/.yaml
```
The rendered version is confusing. Maybe there's a way to fool the "automatic HTML detection" to make the Markdown render as intended?

**Comment by sjjf** [comment]
Aha - well spotted, and thanks for the report. Backticks to the rescue!
