### ISSUE TITLE
RPM  is not installable standalone (missing python library)

### ISSUE THREAD

**Issue by hdb3** [sjjf/md_server#12]
Testing RPM build, on centos7 as both build host and (separate) install destination, the required library xmltodict is not installed.  (But as expected if pip install -r requirements.txt then the service starts as it should).
The systemd log trace follows, but is probably not required to diagnose/confirm this issue!
I installed the RPM so: "yum install /tmp/mdserver/mdserver-0.5.0-1.noarch.rpm".

log trace:
Jun 06 13:08:59 big.sys mdserver[19860]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
Jun 06 13:08:59 big.sys mdserver[19860]: working_set.require(__requires__)
Jun 06 13:08:59 big.sys mdserver[19860]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
Jun 06 13:08:59 big.sys mdserver[19860]: needed = self.resolve(parse_requirements(requirements))
Jun 06 13:08:59 big.sys mdserver[19860]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
Jun 06 13:08:59 big.sys mdserver[19860]: raise DistributionNotFound(req)
Jun 06 13:08:59 big.sys mdserver[19860]: pkg_resources.DistributionNotFound: xmltodict>=0.11.0
Jun 06 13:08:59 big.sys systemd[1]: mdserver.service: main process exited, code=exited, status=1/FAILURE
Jun 06 13:08:59 big.sys systemd[1]: Unit mdserver.service entered failed state.
Jun 06 13:08:59 big.sys systemd[1]: mdserver.service failed.

**Comment by sjjf** [comment]
Not very familiar with `bdist_rpm`, but having a look . . . It looks like the dependencies aren't being added to the spec file, which makes sense since the requirements.txt file only specifies the python packages, not the distro packages. Judging from the mdserver.spec file produced by bdist_rpm, it looks like the following command should produce an installable package:

```
python ./setup.py bdist_rpm --requires 'python-xmltodict>=0.11.0,libvirt-python>=1.2.2,python-bottle>=0.12.0'
```

Could you verify that this command line produces a valid and installable RPM? If so, then I'll add a `setup.cfg` file adding these requirements to the `bdist_rpm` options.

Thanks,
Simon

**Comment by sjjf** [comment]
Okay, some further testing (I managed to get hold of a centos 7 login) shows a couple of things: firstly, the xmltodict and bottle RPMs are in the EPEL repository, and secondly EPEL 7 only has xmltodict 0.9.0. I can't see any changes in xmltodict between 0.9.0 and 0.11.0 that would break anything, but I haven't been able to test that properly - the test script doesn't actually cause mdserver to process any libvirt xml. I'm looking at adding some mocked up tests that do test it, but I'm not there yet.

I've just pushed a branch with the proposed fix for this - a `setup.cfg` that specifies the rpm dependencies, and the adjustments to the requirements to specify xmltodict 0.9.0 - [rpm_build_fix](https://github.com/sjjf/md_server/tree/rpm_build_fix). Can you take a look and see if that works in your environment?

Thanks,
Simon
